### PR TITLE
fix: all the things, a complete re-write

### LINKED ISSUE #3: Component uses _.compose instead of compose-function which is defined in package.json
This is for all 1.x versions;

### PR DESCRIPTION
**Pull request by hongymagic**
Also closes #3

### CODE REVIEW

**Comment by hongymagic** [comment]
@jh-sz @dwendo @markbrownsword any comments?

**Comment by dwendo** [comment]
Had some issues pulling down the npm packages at work. Got it running and
having a look at it all now.

**Comment by markbrownsword** [comment]
Works well. Only comment might be to include in the ReadMe that Node version 0.10.38 is required to run Jest!

**Comment by hongymagic** [comment]
Good point. Technically, the component should be available for other versions of node, only in development you would need node `0.8.x || 0.10.x` as `jest-cli` specifies that. Looks like new `jest-cli` changes all this.

I shall add it to `README.md` regardless.

**Comment by dwendo** [comment]
Nice. Some really good additions here!

Good to go from my point of view.

**Pull request merged**
